### ISSUE TITLE
Logo Proposal for Incognito

### ISSUE THREAD

**Issue by area55git** [ASHWINI-GUPTA/Incognito#10]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Would you like me to design a Logo for Incognito?

**Comment by ASHWINI-GUPTA** [comment]
Yes please. Incognito is open to evolve.

**Comment by area55git** [comment]
Hi, perfect I'll start with the design, do you have any suggestions? what would you like?
I need some information of "Incognito" to have some reference.

**Comment by ASHWINI-GUPTA** [comment]
> Incognito is anonymous message sending application created for colleagues, friends and others, where they can able to share thoughts about you which they were unable to express impersonal.

Example -

**Foo** and **John** are good friends and working on same project, Foo has an attitude problem, everyone in team is wanted to replace Foo but John don't want that and he (John) also don't want to discuss impersonally, it'll make Foo embarrass, Foo uses Incognito so John now can write anonymous message to Foo describing the incident. Now, Foo is improving his behaviour with his teammates and everyone is happy with him.

**Comment by ASHWINI-GUPTA** [comment]
Currently I'm using Font-Awesome (https://fontawesome.com/icons/user-secret?style=solid) Icon.

![image](https://user-images.githubusercontent.com/11544667/39666382-820a9132-50c0-11e8-9166-005e5a0ed2aa.png)

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_INCOGNITO.jpg](https://s7.postimg.cc/hz8j2rqzv/LOGO_PROPOSAL_FOR_INCOGNITO.jpg)](https://postimg.cc/image/vswvrtjl3/)


Hi, if you like this proposal I send you the logos in several formats (PNG, SVG, PDF, JPG).
I can place it in the readme file and make a PR.

You can suggest any change.

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_INCOGNITO_2.jpg](https://s7.postimg.cc/85vx39j9n/LOGO_PROPOSAL_FOR_INCOGNITO_2.jpg)](https://postimg.cc/image/du27u5nlz/)


These suggestions is to use them as Avatar or Icon

**Comment by ASHWINI-GUPTA** [comment]
@area55git I really likes the suggestions.. 

![image](https://user-images.githubusercontent.com/11544667/39772536-2c1f2026-5313-11e8-979e-dead16da3ad1.png)

- But I'm using **Blue** color as primary color for the application. You can refer to the [URL]
(https://incodev.azurewebsites.net/) for a look. So, It will be best if you match the logo color schema.

- I'm open to any kind of suggestions.

**Comment by area55git** [comment]
Ok, I'm going to make the suggested changes

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_INCOGNITO.jpg](https://s9.postimg.cc/kkljhvhmn/LOGO_PROPOSAL_FOR_INCOGNITO.jpg)](https://postimg.cc/image/3k2n974l7/)


What do you think?

**Comment by ASHWINI-GUPTA** [comment]
BIG YESSS.. :-)

**Comment by area55git** [comment]
PR #12

Do not close this Issues, I will send you the link to download the original logos.

**Comment by area55git** [comment]
# [FILE DOWNLOAD](https://drive.google.com/open?id=1MJ1rzcboAwFecliVokQ8NQt24y5yziRo)

[![DERECHOS.jpg](https://s9.postimg.cc/o92yspasf/DERECHOS.jpg)](https://postimg.cc/image/cjyz4qjtn/)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

Thank you very much for accepting my collaboration, if you need a logo for another project you just have to request it and I will be happy to help you.
